Add -fgnu89-inline to CFLAGS
In GCC 5.1 default C standard changed to -std=gnu11. This changed behavior of
inline functions. Build error is:
[  110s] In file included from /home/abuild/rpmbuild/BUILD/tel-plugin-indicator-0.1.62/src/s_indi_main.c:44:0:
[  110s] /home/abuild/rpmbuild/BUILD/tel-plugin-indicator-0.1.62/include/s_indi_log.h:59:14: error: inline function 's_indi_get_log_tag_with_cp_name' declared but never defined [-Werror]
[  110s]  inline char *s_indi_get_log_tag_with_cp_name(const char *cp_name);
[  110s] cc1: all warnings being treated as errors

Changing back to gnu89 inlining mode fixes the issue.

Change-Id: Ie06a93c6282f1b436087a1f16696cf26ec6cf9f6
Signed-off-by: Yury Usishchev <y.usishchev@samsung.com>